# Generated by Django 5.1.2 on 2024-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_alter_nota_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='bimestre',
            field=models.CharField(choices=[('1', '1 Bimestre'), ('2', '2 Bimestre'), ('3', '3 Bimestre'), ('4', '4 Bimestre')], default='1', max_length=1),
        ),
    ]
