# Generated by Django 5.1.2 on 2024-10-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_nota_bimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='notas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.nota'),
        ),
    ]
