# Generated by Django 5.1.2 on 2024-10-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_matricula_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='notas',
        ),
    ]
